os:
  - linux
  - osx
language: rust
cache: cargo
rust:
  - stable
before_script:
  - rustup component add clippy
script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test --verbose