[package]
name = "gclone"
version = "0.1.0"
authors = ["Alec Snyder <linuxbash8@gmail.com>"]
edition = "2018"

[dependencies]
url = "1.7.2"
dirs = "1.0.4"
toml = "0.4.10"
glob = "0.2.11"

[[bin]]
name = "gclone-bin"
path = "src/main.rs"
test = true